name: stream
channels:
- defaults
- ooi
- conda-forge
dependencies:
- nomkl
- cachetools=2.0.0
- geoalchemy2=0.4.0
- cassandra-driver=3.9.0
- concurrentloghandler=0.9.1
- flask=0.12
- futures
- gunicorn=19.7.0
- ion-functions>=2.4.4a
- mock
- msgpack-python=0.4.8
- netcdf4=1.2.4
- nose
- ntplib=0.3.3
- numexpr=2.6.2
- numpy=1.12
- ooi-data=0.0.5
- pandas=0.19.2
- pygsw=0.0.11
- pyproj=1.9.5.1
- python=2.7.14
- quantities
- requests=2.13.0
- requests-mock
- scipy=0.19.0
- simplejson
- sqlalchemy=1.1.5
- xarray=0.9.2
