name: stream
channels:
- defaults
- ooi
- conda-forge
dependencies:
- cachetools=2.0.0
- geoalchemy2=0.4.0
- cassandra-driver=2.7.2
- concurrentloghandler=0.9.1
- flask=0.12
- futures=2.2.0
- gunicorn=19.7.0
- ion-functions=2.2.0
- msgpack-python=0.4.8
- netcdf4=1.2.4
- ntplib=0.3.3
- numexpr=2.6.2
- numpy=1.12
- ooi-data=0.0.5
- pandas=0.19.2
- pygsw=0.0.11
- python=2.7.11
- requests=2.13.0
- scipy=0.19.0
- simplejson=3.10.0
- sqlalchemy=1.1.5
- xarray=0.8.2
