DEBUG = False

CASSANDRA_CONTACT_POINTS = ['127.0.0.1']
CASSANDRA_KEYSPACE = 'ooi'
CASSANDRA_CONNECT_TIMEOUT = 60
CASSANDRA_FETCH_SIZE = 1000
CASSANDRA_DEFAULT_TIMEOUT = 60

ANNOTATION_URL = 'http://localhost:12580/annotations/find/'

POOL_SIZE = 4

LOGGING_CONFIG='logging.conf'
