#!/bin/bash

HERE=$(pwd)

PIDFILE="$HERE/stream_engine.pid"
NAME="Stream Engine"
timestamp=`date +%F-%H-%M-%S`

start(){
    echo "Starting Stream Engine..."
    if [ -f $PIDFILE ]; then
        # PIDFILE exists, but the corresponding process does not
        if [ ! -f /proc/$(cat $PIDFILE)/status ]; then
            rm $PIDFILE
        fi
    fi

    if [ ! -f $PIDFILE ]; then
        export OOI_GUNICORN_LOG_LOC=$HERE
        gunicorn --pythonpath $HERE --log-config $HERE/logging.conf --daemon -p $PIDFILE --config $HERE/gunicorn_config.py engine.routes:app
    else
        echo "$NAME: Trying to start stream engine, but pid exists"
    fi

}

stop(){
    echo "Stopping Stream Engine..."
    if [ -f $PIDFILE ]; then
        kill $(<$PIDFILE)
        rm $PIDFILE
    else
        echo "$NAME: Trying to stop stream engine, but pid does not exist"
        rm $PIDFILE
    fi
}

reload(){
    echo "Reloading Stream Engine..."
    if [ -f $PIDFILE ]; then
        kill -HUP $(<$PIDFILE)
        rm $PIDFILE
    else
        echo "$NAME: Trying to reload stream engine, but pid does not exist"
        rm $PIDFILE
    fi
}

case $1 in
    start)
        start
        ;;
    stop)
        stop
        ;;
    reload)
        reload
        ;;
    restart)
        stop
        start
        ;;
    status)
        [ -f $PIDFILE ] && echo "$NAME: "$(<$PIDFILE) || echo "Stream Engine:"
        ;;
    *)
        echo "Usage: manage-streamng (start|stop|reload|restart|status)"
        ;;
esac
