#!/bin/bash

HERE=$(dirname $(readlink -f $BASH_SOURCE))

if [ -z ${STREAM_ENGINE_PYTHON:+x} ]
then
    #PYTHON_PATH="$HERE/python27"
    PYTHON_PATH="/home/race/python27"
else
    PYTHON_PATH=$STREAM_ENGINE_PYTHON
fi
STREAMNG_PID="$HERE/stream_engine.pid"
NAME="Stream Engine"
timestamp=`date +%F-%H-%M-%S`

source "$PYTHON_PATH/getenv.sh"

start(){
    echo "Starting Stream Engine..."
    if [ ! -f $STREAMNG_PID ]; then
        export OOI_GUNICORN_LOG_LOC=$HERE
        gunicorn --pythonpath $HERE --log-config $HERE/logging.conf --daemon -p $STREAMNG_PID --config $HERE/gunicorn_config.py engine.routes:app
        export OOI_GUNICORN_LOG_LOC=
        #gunicorn --daemon -p $STREAMNG_PID --config $HERE/gunicorn_config.py engine.routes:app > "/home/race/stream_engine/${timestamp}.log" 2>&1 &
    else
        echo "$NAME: Trying to start stream engine, but pid exists"
    fi
        
}

stop(){
    echo "Stopping Stream Engine..."
    if [ -f $STREAMNG_PID ]; then
        kill $(<$STREAMNG_PID)
    else
        echo "$NAME: Trying to stop stream engine, but pid does not exist"
    fi
}

case $1 in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    status)
        [ -f $STREAMNG_PID ] && echo "$NAME: "$(<$STREAMNG_PID) || echo "Stream Engine:"
        ;;
    *)
        echo "Usage: manage-streamng (start|stop|restart|status)"
        ;;
esac
